# Generated by Django 3.2.5 on 2021-08-29 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('DebitCardNumber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('EmailId', models.CharField(max_length=40)),
                ('Balance', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('EmailId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('Amount', models.BigIntegerField()),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
