# Generated by Django 3.2.5 on 2021-09-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0002_account_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='DebitCardNumber',
            new_name='CustomerId',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Balance',
        ),
        migrations.AddField(
            model_name='account',
            name='DepositAcctId',
            field=models.IntegerField(null=True),
        ),
    ]
