# Generated by Django 3.2.5 on 2021-09-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0003_auto_20210930_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='DepositAcctId',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
