# Generated by Django 3.2.5 on 2021-10-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0004_alter_account_depositacctid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='DebitCardId',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
