# Generated by Django 3.2.5 on 2021-10-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0005_account_debitcardid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='account',
            name='DebitCardId',
        ),
        migrations.RemoveField(
            model_name='account',
            name='DepositAcctId',
        ),
        migrations.RemoveField(
            model_name='account',
            name='EmailId',
        ),
    ]
