# Generated by Django 3.2.5 on 2021-10-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0006_auto_20211007_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='CustomerId',
            new_name='CardholderId',
        ),
    ]
