# Generated by Django 3.2.5 on 2021-10-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0007_rename_customerid_account_cardholderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='CardholderId',
            new_name='CustomerId',
        ),
    ]
