# Generated by Django 3.2.5 on 2021-10-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0008_rename_cardholderid_account_customerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='EmailId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
