# Generated by Django 3.2.5 on 2021-10-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0009_account_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='UserId',
            field=models.CharField(max_length=28, null=True),
        ),
    ]
