# Generated by Django 3.2.5 on 2021-10-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0010_account_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Auth_Level',
            field=models.IntegerField(default=0),
        ),
    ]
