# Generated by Django 3.2.5 on 2021-10-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0011_account_auth_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Auth_Level',
            field=models.IntegerField(default=1),
        ),
    ]
