# Generated by Django 3.2.5 on 2021-10-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0012_alter_account_auth_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='UserId',
        ),
        migrations.AddField(
            model_name='account',
            name='CardholderId',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='VerificationId',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
