# Generated by Django 3.2.5 on 2021-10-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0013_auto_20211028_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='EmailId',
        ),
    ]
