# Generated by Django 3.2.5 on 2021-10-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0015_account_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='CustomerId',
            new_name='user',
        ),
    ]
