# Generated by Django 3.2.5 on 2021-11-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0016_rename_customerid_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='BdayVerificationId',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='CardApplicationId',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
