# Generated by Django 3.2.5 on 2021-11-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0017_auto_20211105_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='BdayVerificationId',
        ),
        migrations.AddField(
            model_name='account',
            name='UserToken',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
