# Generated by Django 3.2.5 on 2021-11-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0018_auto_20211105_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='CardApplicationId',
        ),
        migrations.RemoveField(
            model_name='account',
            name='CardholderId',
        ),
    ]
