# Generated by Django 3.2.5 on 2021-11-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0019_auto_20211106_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='BirthdayVerificationId',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
