# Generated by Django 3.2.5 on 2021-12-01 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0020_account_birthdayverificationid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Auth_Level',
        ),
        migrations.RemoveField(
            model_name='account',
            name='BirthdayVerificationId',
        ),
        migrations.RemoveField(
            model_name='account',
            name='UserToken',
        ),
        migrations.RemoveField(
            model_name='account',
            name='VerificationId',
        ),
    ]
