# Generated by Django 3.2.5 on 2021-12-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0021_auto_20211130_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Phone',
        ),
        migrations.AddField(
            model_name='account',
            name='Email',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
