# Generated by Django 3.2.5 on 2022-01-05 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atm_functions', '0022_auto_20211205_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('currencyName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contract', models.CharField(max_length=255, unique=True)),
                ('blockchain', models.CharField(max_length=21)),
                ('network', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionB',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('transactionType', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('addressEmitter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emmiter_addresss', to='atm_functions.address')),
                ('addressReceptor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptor_addresss', to='atm_functions.address')),
                ('currencyName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atm_functions.cryptocurrency')),
                ('emitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emmiter_email', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptor_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionA',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('transactionType', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atm_functions.address')),
                ('currencyName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atm_functions.cryptocurrency')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('currencyName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atm_functions.cryptocurrency')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='currencyName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atm_functions.cryptocurrency'),
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
