# Generated by Django 3.2.5 on 2022-01-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0023_auto_20220105_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='walletAddress',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
