# Generated by Django 3.2.5 on 2022-01-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0024_auto_20220105_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiona',
            old_name='transactionId',
            new_name='idA',
        ),
        migrations.RenameField(
            model_name='transactionb',
            old_name='transactionId',
            new_name='idB',
        ),
    ]
