# Generated by Django 3.2.5 on 2022-01-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0025_auto_20220106_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiona',
            name='transactionId',
            field=models.CharField(max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionb',
            name='transactionId',
            field=models.CharField(max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
