# Generated by Django 3.2.5 on 2022-01-07 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0026_auto_20220106_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='currencyName',
            new_name='currency_name',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='currencyName',
            new_name='currency_name',
        ),
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='currencyName',
            new_name='currency_name',
        ),
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='walletAddress',
            new_name='wallet_address',
        ),
        migrations.RenameField(
            model_name='transactiona',
            old_name='currencyName',
            new_name='currency_name',
        ),
        migrations.RenameField(
            model_name='transactiona',
            old_name='idA',
            new_name='id_a',
        ),
        migrations.RenameField(
            model_name='transactiona',
            old_name='transactionId',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='transactionb',
            old_name='addressEmitter',
            new_name='address_emitter',
        ),
        migrations.RenameField(
            model_name='transactionb',
            old_name='addressReceptor',
            new_name='address_receptor',
        ),
        migrations.RenameField(
            model_name='transactionb',
            old_name='currencyName',
            new_name='currency_name',
        ),
        migrations.RenameField(
            model_name='transactionb',
            old_name='idB',
            new_name='id_b',
        ),
        migrations.RenameField(
            model_name='transactionb',
            old_name='transactionId',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='transactionb',
            old_name='transactionType',
            new_name='transaction_type',
        ),
    ]
