# Generated by Django 3.2.5 on 2022-01-08 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0027_auto_20220106_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='currency_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm_functions.cryptocurrency'),
        ),
    ]
