# Generated by Django 3.2.5 on 2022-01-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0028_alter_address_currency_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiona',
            old_name='transactionType',
            new_name='transaction_type',
        ),
    ]
