# Generated by Django 3.2.5 on 2022-01-08 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atm_functions', '0031_auto_20220108_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionb',
            name='address_receptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptor_addresss', to='atm_functions.address'),
        ),
        migrations.AlterField(
            model_name='transactionb',
            name='receptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptor_email', to=settings.AUTH_USER_MODEL),
        ),
    ]
