# Generated by Django 3.2.5 on 2022-01-08 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0032_auto_20220108_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionb',
            old_name='amount_colateral',
            new_name='amount_collateral',
        ),
    ]
