# Generated by Django 3.2.5 on 2022-01-10 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0034_alter_transactionb_amount_collateral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionb',
            name='address_emitter',
        ),
        migrations.RemoveField(
            model_name='transactionb',
            name='address_receptor',
        ),
    ]
