# Generated by Django 3.2.5 on 2022-01-23 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0036_auto_20220123_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 0, 36, 34, 24912)),
        ),
    ]
