# Generated by Django 3.2.5 on 2022-01-24 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0039_alter_address_expiration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 22, 48, 9, 185135), null=True),
        ),
    ]
