# Generated by Django 3.2.5 on 2022-01-25 07:20

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0040_alter_address_expiration_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiona',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 1, 19, 54, 385390), null=True),
        ),
    ]
