# Generated by Django 3.2.5 on 2022-03-06 07:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0041_auto_20220125_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 7, 7, 48, 815736, tzinfo=utc), null=True),
        ),
    ]
