# Generated by Django 3.2.5 on 2022-03-09 02:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0042_alter_address_expiration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 2, 23, 55, 864679, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='transactiona',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='atm_functions.address'),
        ),
    ]
