# Generated by Django 3.2.5 on 2022-03-12 22:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0043_auto_20220308_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiona',
            name='internal_state',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 22, 52, 1, 863137, tzinfo=utc), null=True),
        ),
    ]
