# Generated by Django 3.2.5 on 2022-04-10 22:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0044_auto_20220312_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 22, 3, 13, 95763, tzinfo=utc), null=True),
        ),
    ]
