# Generated by Django 3.2.5 on 2022-04-14 00:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0046_auto_20220413_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 0, 56, 50, 331156, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
