# Generated by Django 3.2.5 on 2022-04-14 01:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0047_auto_20220413_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit_grade',
            field=models.CharField(default='FFF', max_length=4),
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 1, 25, 32, 88786, tzinfo=utc), null=True),
        ),
    ]
