# Generated by Django 3.2.5 on 2022-04-28 22:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atm_functions', '0049_auto_20220421_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 22, 40, 41, 911006, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='TransactionC',
            fields=[
                ('id_c', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=38, unique=True)),
                ('crypto_id_from', models.CharField(max_length=10)),
                ('crypto_id_swap_to', models.CharField(max_length=10)),
                ('address_destination', models.CharField(max_length=100)),
                ('address_refund', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('network_fee', models.DecimalField(decimal_places=8, max_digits=15)),
                ('amount_estimated_return', models.DecimalField(decimal_places=8, max_digits=15)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
