# Generated by Django 3.2.5 on 2022-05-02 02:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0051_auto_20220501_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionc',
            old_name='amount_estimated_return',
            new_name='amount_estimated',
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 2, 18, 45, 495356, tzinfo=utc), null=True),
        ),
    ]
