# Generated by Django 3.2.5 on 2022-05-08 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0052_auto_20220501_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='currency_type',
            field=models.CharField(default='PAYMENTS', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 5, 23, 51, 71648, tzinfo=utc), null=True),
        ),
    ]
