# Generated by Django 3.2.5 on 2022-05-23 01:45

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0054_auto_20220522_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainwill',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 1, 45, 45, 521839, tzinfo=utc), null=True),
        ),
    ]
