# Generated by Django 3.2.5 on 2022-05-25 23:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0055_auto_20220522_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(max_length=57, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 23, 15, 6, 544495, tzinfo=utc), null=True),
        ),
    ]
