# Generated by Django 3.2.5 on 2022-05-30 03:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0056_auto_20220524_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 3, 20, 52, 851805, tzinfo=utc), null=True),
        ),
    ]
