# Generated by Django 3.2.5 on 2022-06-05 22:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0057_alter_address_expiration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 11, 22, 50, 32, 600180, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='birth_country',
            field=models.CharField(max_length=57, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='full_legal_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='relationship',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='will_percentage',
            field=models.IntegerField(null=True),
        ),
    ]
