# Generated by Django 3.2.5 on 2022-06-14 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0061_auto_20220613_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='official_name',
        ),
        migrations.AddField(
            model_name='business',
            name='system_name',
            field=models.CharField(max_length=57),
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 1, 23, 7, 62536, tzinfo=utc), null=True),
        ),
    ]
