# Generated by Django 3.2.5 on 2022-06-15 01:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0062_auto_20220613_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id_wl', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 1, 14, 53, 68515, tzinfo=utc), null=True),
        ),
    ]
