# Generated by Django 3.2.5 on 2022-06-25 19:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0063_auto_20220614_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainwill',
            name='transaction_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 1, 19, 17, 30, 223373, tzinfo=utc), null=True),
        ),
    ]
