# Generated by Django 3.2.5 on 2022-06-30 00:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0064_auto_20220625_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='net_worth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 0, 8, 20, 139397, tzinfo=utc), null=True),
        ),
    ]
