# Generated by Django 3.2.5 on 2022-06-30 01:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atm_functions', '0065_auto_20220629_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 1, 39, 55, 67566, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='UserAssets',
            fields=[
                ('id_asset', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=57, null=True)),
                ('worth', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('extra_field', models.CharField(max_length=57, null=True)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
