# Generated by Django 3.2.5 on 2022-06-30 04:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0066_auto_20220629_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 4, 51, 15, 98263, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userassets',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
