# Generated by Django 3.2.5 on 2022-07-03 23:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atm_functions', '0067_auto_20220629_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 23, 46, 7, 993641, tzinfo=utc), null=True),
        ),
    ]
