# Generated by Django 3.2.5 on 2022-07-23 23:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0068_auto_20220703_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalCurrency',
            fields=[
                ('id_currency', models.AutoField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('currency_type', models.CharField(max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=15)),
            ],
        ),
        migrations.AddField(
            model_name='balance',
            name='currency_type',
            field=models.CharField(default='CRYPTO', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 23, 52, 33, 866224, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='currency_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atm_functions.cryptocurrency'),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id_currency', models.AutoField(primary_key=True, serialize=False)),
                ('currency_type', models.CharField(max_length=10)),
                ('currency_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('crypto_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atm_functions.cryptocurrency')),
                ('digital_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atm_functions.digitalcurrency')),
            ],
        ),
        migrations.AddField(
            model_name='balance',
            name='digital_currency_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atm_functions.digitalcurrency'),
        ),
    ]
