# Generated by Django 3.2.5 on 2022-08-05 23:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atm_functions', '0071_auto_20220804_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 23, 16, 17, 352283, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='StripeTransactions',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('payment_intent', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('transaction_type', models.CharField(max_length=15)),
                ('transaction_state', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
