# Generated by Django 3.2.5 on 2022-08-05 23:26

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atm_functions', '0073_auto_20220805_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StripeTransactions',
            new_name='StripeTransaction',
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 23, 26, 37, 647225, tzinfo=utc), null=True),
        ),
    ]
