# Generated by Django 3.2.5 on 2022-08-05 23:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0074_auto_20220805_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripetransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='stripetransaction',
            name='stripe_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm_functions.stripeaccount'),
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 23, 32, 45, 145403, tzinfo=utc), null=True),
        ),
    ]
