# Generated by Django 3.2.5 on 2022-08-06 03:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0076_auto_20220805_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='id',
        ),
        migrations.AddField(
            model_name='business',
            name='id_business',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 3, 15, 25, 425619, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
