# Generated by Django 3.2.5 on 2022-08-06 04:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atm_functions', '0077_auto_20220805_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='system_username',
        ),
        migrations.RemoveField(
            model_name='business',
            name='system_name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='username',
        ),
        migrations.AddField(
            model_name='business',
            name='logo_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 4, 2, 26, 892910, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='DynamicUsername',
            fields=[
                ('id_username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('username_type', models.CharField(max_length=10, null=True)),
                ('business_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atm_functions.business')),
                ('user_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
