# Generated by Django 3.2.5 on 2022-08-06 04:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0080_auto_20220805_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 4, 20, 55, 474668, tzinfo=utc), null=True),
        ),
    ]
