# Generated by Django 3.2.5 on 2022-08-06 04:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0081_auto_20220805_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='username',
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 4, 21, 32, 770412, tzinfo=utc), null=True),
        ),
    ]
