# Generated by Django 3.2.5 on 2022-08-08 00:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atm_functions', '0084_auto_20220807_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 0, 21, 40, 447373, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='TransactionC',
            fields=[
                ('id_a', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('currency_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atm_functions.digitalcurrency')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
