# Generated by Django 3.2.5 on 2022-08-08 00:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0085_auto_20220807_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionc',
            old_name='email',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 0, 23, 12, 682051, tzinfo=utc), null=True),
        ),
    ]
