# Generated by Django 3.2.5 on 2022-08-08 23:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0088_alter_address_expiration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 23, 49, 39, 742766, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userassets',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
