# Generated by Django 3.2.5 on 2022-08-13 01:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atm_functions', '0089_auto_20220808_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 1, 8, 15, 111278, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('id_referal', models.AutoField(primary_key=True, serialize=False)),
                ('referral_code', models.CharField(max_length=30, unique=True)),
                ('user_referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_referred', to=settings.AUTH_USER_MODEL)),
                ('user_referring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_referring', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
