# Generated by Django 3.2.5 on 2022-08-14 07:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('atm_functions', '0090_auto_20220812_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicusername',
            name='business_reference2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_owner_business', to='businesses.business'),
        ),
    ]
