# Generated by Django 3.2.5 on 2022-08-14 07:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0091_auto_20220814_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicusername',
            name='business_reference',
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 7, 37, 32, 395798, tzinfo=utc), null=True),
        ),
    ]
