# Generated by Django 3.2.5 on 2022-08-14 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0092_auto_20220814_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicusername',
            old_name='business_reference2',
            new_name='business_reference',
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 7, 38, 7, 504614, tzinfo=utc), null=True),
        ),
    ]
