# Generated by Django 3.2.5 on 2022-08-18 02:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0095_alter_address_expiration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 2, 18, 2, 637028, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='CreditsTransaction',
            fields=[
                ('id_a', models.AutoField(primary_key=True, serialize=False)),
                ('sender_username', models.CharField(max_length=30, null=True)),
                ('receiver_username', models.CharField(max_length=30, null=True)),
                ('transaction_type', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('digital_currency_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atm_functions.digitalcurrency')),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to='atm_functions.account')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to='atm_functions.account')),
            ],
        ),
    ]
