# Generated by Django 3.2.5 on 2022-08-20 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0099_auto_20220818_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditstransaction',
            name='transaction_state',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 20, 32, 32, 644180, tzinfo=utc), null=True),
        ),
        migrations.DeleteModel(
            name='TransactionC',
        ),
    ]
