# Generated by Django 3.2.5 on 2022-08-20 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0100_auto_20220820_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StripeTransaction',
            new_name='TransactionStripe',
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 20, 40, 31, 146350, tzinfo=utc), null=True),
        ),
    ]
