# Generated by Django 3.2.5 on 2022-08-20 20:44

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atm_functions', '0101_auto_20220820_1540'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreditsTransaction',
            new_name='TransactionCredits',
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 20, 44, 42, 787476, tzinfo=utc), null=True),
        ),
    ]
