# Generated by Django 3.2.5 on 2022-08-20 20:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0102_auto_20220820_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioncredits',
            name='transaction_state',
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 20, 48, 30, 933423, tzinfo=utc), null=True),
        ),
    ]
