# Generated by Django 3.2.5 on 2022-08-20 20:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0103_auto_20220820_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactioncredits',
            old_name='state',
            new_name='transaction_state',
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 20, 48, 47, 119079, tzinfo=utc), null=True),
        ),
    ]
