# Generated by Django 3.2.5 on 2022-08-20 22:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0104_auto_20220820_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncredits',
            name='note',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 22, 29, 26, 183649, tzinfo=utc), null=True),
        ),
    ]
