# Generated by Django 3.2.5 on 2022-08-21 02:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0105_auto_20220820_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactioncredits',
            old_name='id_a',
            new_name='id_transaction',
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 2, 59, 34, 543204, tzinfo=utc), null=True),
        ),
    ]
