# Generated by Django 3.2.5 on 2022-08-24 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0107_auto_20220823_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_lob',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 2, 44, 37, 364908, tzinfo=utc), null=True),
        ),
    ]
