# Generated by Django 3.2.5 on 2022-08-26 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0108_auto_20220823_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 22, 8, 55, 78055, tzinfo=utc), null=True),
        ),
    ]
