# Generated by Django 3.2.5 on 2022-08-30 22:41

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atm_functions', '0113_alter_address_expiration_datetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referal',
            new_name='Referral',
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 22, 41, 35, 303478, tzinfo=utc), null=True),
        ),
    ]
