# Generated by Django 3.2.5 on 2022-09-02 02:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0115_auto_20220831_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='credits',
            field=models.DecimalField(decimal_places=8, default=10, max_digits=18),
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 2, 9, 1, 246468, tzinfo=utc), null=True),
        ),
    ]
