# Generated by Django 3.2.5 on 2022-09-06 03:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0122_auto_20220903_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicusername',
            name='referral_credits',
            field=models.DecimalField(decimal_places=6, default=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 3, 52, 48, 955720, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 3, 52, 48, 957719, tzinfo=utc), null=True),
        ),
    ]
