# Generated by Django 3.2.5 on 2022-11-10 02:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atm_functions', '0127_auto_20221025_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='extra_data',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 2, 4, 10, 781683, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 2, 4, 10, 785684, tzinfo=utc), null=True),
        ),
    ]
