# Generated by Django 3.2.5 on 2022-08-14 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id_business', models.AutoField(primary_key=True, serialize=False)),
                ('official_name', models.CharField(max_length=57)),
                ('system_name', models.CharField(max_length=57)),
                ('logo_url', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=30)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
