# Generated by Django 3.2.5 on 2022-09-08 03:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_purchasehistory_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesses', '0003_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='BusinessMessages',
        ),
    ]
