# Generated by Django 3.2.5 on 2022-09-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_rename_messages_businessmessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmessages',
            name='business',
        ),
        migrations.RemoveField(
            model_name='businessmessages',
            name='user',
        ),
        migrations.AddField(
            model_name='businessmessages',
            name='message_sender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
