# Generated by Django 3.2.5 on 2022-08-27 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_system_category'),
        ('marketplace', '0002_products_digital_service_reference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
