# Generated by Django 3.2.5 on 2022-08-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalservice',
            name='calendar_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='digitalservice',
            name='extra_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='digitalservice',
            name='video_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
