# Generated by Django 3.2.5 on 2021-08-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmailId', models.CharField(max_length=50)),
                ('DebitCardNumber', models.BigIntegerField()),
                ('Pin', models.CharField(max_length=4)),
                ('verify', models.BooleanField(default=False)),
            ],
        ),
    ]
