# Generated by Django 3.2.5 on 2021-09-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='Country',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
