# Generated by Django 3.2.5 on 2021-10-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_status_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='Country',
        ),
    ]
