# Generated by Django 3.2.5 on 2021-10-08 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_status_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='id',
        ),
        migrations.AddField(
            model_name='status',
            name='aptoid',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, primary_key=True, serialize=False, verbose_name='AptoID'),
            preserve_default=False,
        ),
    ]
