# Generated by Django 3.2.5 on 2021-10-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_status_regtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='aptoid',
            new_name='ver_id',
        ),
    ]
