# Generated by Django 3.2.5 on 2021-10-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_aptoid_status_ver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='Phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
