# Generated by Django 3.2.5 on 2021-10-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_status_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='Phone',
        ),
    ]
